const PDFDocument = require('pdfkit');

/**
 * Generates a hospital receipt PDF and writes it to a stream.
 * @param {Object} receipt - The Receipt mongoose document
 * @param {Object} patient - The Patient mongoose document
 * @param {Object} user - The User document who generated it
 * @param {WritableStream} writeStream - Stream to pipe PDF to
 */
const generateReceiptPDF = (receipt, patient, user, writeStream) => {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  // Pipe output
  doc.pipe(writeStream);

  // --- HEADER SECTION ---
  doc.fillColor('#1A365D') // Dark blue brand color
     .fontSize(20)
     .text('ICSR CANCER INSTITUTE', { align: 'left', bold: true });
  
  doc.fillColor('#4A5568')
     .fontSize(9)
     .text('Cancer Patient Registry & Research Management System (CPRRMS)', { align: 'left' })
     .text('Plot 12, Research District, Tech City, IN', { align: 'left' })
     .text('Contact: support@icsr.org | +91 11-2345-6789', { align: 'left' });

  // Horizontal divider
  doc.moveTo(50, 115).lineTo(545, 115).strokeColor('#E2E8F0').lineWidth(1).stroke();

  doc.moveDown(2);

  // --- TITLE & DATE ---
  doc.fillColor('#2D3748')
     .fontSize(16)
     .text('PAYMENT RECEIPT', { align: 'center', underline: true });
  
  doc.moveDown(1);

  // --- DETAILS ROW (Two column layout) ---
  const leftColX = 50;
  const rightColX = 320;
  let currentY = doc.y;

  // Left Column: Receipt Info
  doc.fillColor('#2D3748').fontSize(10);
  doc.text(`Receipt Number:`, leftColX, currentY, { bold: true });
  doc.fillColor('#1A202C').text(receipt.receiptNumber, leftColX + 90, currentY);

  doc.fillColor('#2D3748');
  doc.text(`Receipt Date:`, leftColX, currentY + 18);
  doc.fillColor('#1A202C').text(new Date(receipt.createdAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit'
  }), leftColX + 90, currentY + 18);

  doc.fillColor('#2D3748');
  doc.text(`Payment Mode:`, leftColX, currentY + 36);
  doc.fillColor('#1A202C').text(receipt.paymentMode, leftColX + 90, currentY + 36);

  // Right Column: Patient Info
  doc.fillColor('#2D3748');
  doc.text(`Patient ID:`, rightColX, currentY);
  doc.fillColor('#1A202C').text(patient.patientId, rightColX + 80, currentY);

  doc.fillColor('#2D3748');
  doc.text(`Patient Name:`, rightColX, currentY + 18);
  doc.fillColor('#1A202C').text(patient.name, rightColX + 80, currentY + 18);

  doc.fillColor('#2D3748');
  doc.text(`Phone:`, rightColX, currentY + 36);
  doc.fillColor('#1A202C').text(patient.contactNumber, rightColX + 80, currentY + 36);

  doc.moveDown(3.5);

  // --- BILLING TABLE ---
  currentY = doc.y + 10;
  
  // Table Header
  doc.rect(50, currentY, 495, 20).fill('#2B6CB0'); // blue header bg
  doc.fillColor('#FFFFFF').fontSize(10);
  doc.text('Description', 60, currentY + 5);
  doc.text('Amount (INR)', 450, currentY + 5, { align: 'right', width: 80 });

  // Table Body Row
  currentY += 20;
  doc.rect(50, currentY, 495, 35).fill('#F7FAFC'); // light grey body bg
  doc.fillColor('#2D3748');
  doc.text(receipt.description || 'Medical Registry Processing Fee', 60, currentY + 12, { width: 380 });
  doc.text(`Rs. ${receipt.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 450, currentY + 12, { align: 'right', width: 80 });

  // Table Border
  doc.rect(50, currentY - 20, 495, 55).strokeColor('#CBD5E0').lineWidth(1).stroke();

  currentY += 35;

  // --- TOTAL ---
  doc.moveDown(1);
  currentY = doc.y;
  doc.fillColor('#1A202C').fontSize(12);
  doc.text('Total Paid:', 320, currentY, { bold: true });
  doc.fillColor('#2B6CB0').text(`Rs. ${receipt.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 450, currentY, { align: 'right', width: 80, bold: true });

  // Divider
  doc.moveDown(2);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E2E8F0').lineWidth(0.5).stroke();
  doc.moveDown(1.5);

  // --- FOOTER & SIGNATURES ---
  currentY = doc.y;
  doc.fillColor('#718096').fontSize(9);
  doc.text(`Generated by: ${user.name} (${user.role})`, 50, currentY);
  
  doc.text('Authorized Signature', 400, currentY, { align: 'center', width: 145 });
  doc.moveTo(400, currentY + 40).lineTo(545, currentY + 40).strokeColor('#A0AEC0').stroke();
  doc.text('ICSR Registry Office', 400, currentY + 45, { align: 'center', width: 145 });

  doc.moveDown(5);
  doc.fillColor('#A0AEC0')
     .fontSize(8)
     .text('This is a computer-generated document. No physical signature is required.', { align: 'center' });

  // End Document
  doc.end();
};

module.exports = {
  generateReceiptPDF
};
